SELECT
	TABLE_CATALOG,
	TABLE_SCHEMA,
	TABLE_NAME,
	TABLE_TYPE
FROM
	INFORMATION_SCHEMA.TABLES
WHERE
	TABLE_TYPE = 'BASE TABLE'
	AND TABLE_NAME != 'dtProperties'
	AND TABLE_CATALOG = '#DatabaseName#'
ORDER BY TABLE_NAME
